export const codingPrompts = [
	{
		id: 1,
		title: "Code Snippet Generator",
		description:
			"Generate code snippets for various programming languages quickly and accurately.",
		image: "/browse/code-snippet.png",
		price: 0.05,
		category: "Coding",
		rating: 4.7,
		seller: "CodeMaster.sol",
	},
	{
		id: 2,
		title: "Debugging Assistant",
		description:
			"Analyze your code and suggest fixes for common bugs and issues.",
		image: "/browse/debugging.png",
		price: 0.1,
		category: "Coding",
		rating: 4.8,
		seller: "DebugPro.sol",
	},
	{
		id: 3,
		title: "Algorithm Optimizer",
		description:
			"Optimize your algorithms for improved performance and efficiency.",
		image: "/browse/algorithm.png",
		price: 0.12,
		category: "Coding",
		rating: 4.6,
		seller: "AlgoGenius.sol",
	},
	{
		id: 4,
		title: "API Endpoint Generator",
		description:
			"Quickly generate RESTful API endpoints with integrated documentation.",
		image: "/browse/api.png",
		price: 0.08,
		category: "Coding",
		rating: 4.5,
		seller: "APIMaker.sol",
	},
	{
		id: 5,
		title: "Frontend Component Builder",
		description:
			"Design and build reusable UI components for your web applications.",
		image: "/browse/frontend.png",
		price: 0.15,
		category: "Coding",
		rating: 4.9,
		seller: "UIWizard.sol",
	},
	{
		id: 6,
		title: "Backend Service Generator",
		description:
			"Generate robust backend services with optimized database connections.",
		image: "/browse/backend.png",
		price: 0.2,
		category: "Coding",
		rating: 4.8,
		seller: "BackendGuru.sol",
	},
	{
		id: 7,
		title: "Full Stack Template Creator",
		description:
			"Kickstart your project with a full stack template pre-configured for development.",
		image: "/browse/fullstack.png",
		price: 0.18,
		category: "Coding",
		rating: 4.7,
		seller: "StackHero.sol",
	},
	{
		id: 8,
		title: "Code Refactoring Tool",
		description:
			"Improve your code quality by using automated refactoring tools.",
		image: "/browse/code-refactoring.png",
		price: 0.09,
		category: "Coding",
		rating: 4.4,
		seller: "CleanCode.sol",
	},
	{
		id: 9,
		title: "Unit Test Generator",
		description:
			"Automatically generate unit tests for your codebase to improve reliability.",
		image: "/browse/unit-test.png",
		price: 0.11,
		category: "Coding",
		rating: 4.6,
		seller: "TestPro.sol",
	},
	{
		id: 10,
		title: "Performance Profiler",
		description:
			"Analyze your application performance and identify bottlenecks.",
		image: "/browse/performance.png",
		price: 0.14,
		category: "Coding",
		rating: 4.8,
		seller: "Speedy.sol",
	},
];

export const marketingPrompts = [
	{
		id: 11,
		title: "Social Media Ad Creator",
		description:
			"Generate eye-catching social media ads to boost your brand's engagement.",
		image: "/browse/social-media.png",
		price: 0.12,
		category: "Marketing",
		rating: 4.7,
		seller: "AdWizard.sol",
	},
	{
		id: 12,
		title: "Email Campaign Generator",
		description:
			"Create effective email marketing campaigns with targeted messaging.",
		image: "/browse/email-campaign.png",
		price: 0.1,
		category: "Marketing",
		rating: 4.8,
		seller: "MailMaster.sol",
	},
	{
		id: 13,
		title: "SEO Content Assistant",
		description:
			"Optimize your website content for better search engine rankings.",
		image: "/browse/seo.png",
		price: 0.09,
		category: "Marketing",
		rating: 4.6,
		seller: "SEOGuru.sol",
	},
	{
		id: 14,
		title: "Campaign Performance Analyzer",
		description: "Analyze your marketing campaign data to optimize ROI.",
		image: "/browse/campaign.png",
		price: 0.15,
		category: "Marketing",
		rating: 4.8,
		seller: "CampaignPro.sol",
	},
	{
		id: 15,
		title: "Brand Voice Generator",
		description: "Develop a consistent brand voice and messaging strategy.",
		image: "/browse/brand-voice.png",
		price: 0.13,
		category: "Marketing",
		rating: 4.7,
		seller: "VoiceCraft.sol",
	},
	{
		id: 16,
		title: "Content Calendar Planner",
		description: "Plan and schedule your marketing content effectively.",
		image: "/browse/content.png",
		price: 0.1,
		category: "Marketing",
		rating: 4.5,
		seller: "PlanIt.sol",
	},
	{
		id: 17,
		title: "Market Trend Reporter",
		description:
			"Stay updated with the latest market trends and industry insights.",
		image: "/browse/market.png",
		price: 0.11,
		category: "Marketing",
		rating: 4.6,
		seller: "TrendSetter.sol",
	},
	{
		id: 18,
		title: "Ad Copy Generator",
		description: "Produce compelling ad copy for various platforms with ease.",
		image: "/browse/ad-copy.png",
		price: 0.08,
		category: "Marketing",
		rating: 4.4,
		seller: "CopyKing.sol",
	},
	{
		id: 19,
		title: "Influencer Outreach Assistant",
		description:
			"Identify and connect with influencers to amplify your brand's message.",
		image: "/browse/influencer.png",
		price: 0.14,
		category: "Marketing",
		rating: 4.7,
		seller: "Influence.sol",
	},
	{
		id: 20,
		title: "Campaign Budget Optimizer",
		description:
			"Optimize your marketing budget allocation for maximum impact.",
		image: "/browse/campaign-budget.png",
		price: 0.16,
		category: "Marketing",
		rating: 4.8,
		seller: "BudgetPro.sol",
	},
];

export const creativeWritingPrompts = [
	{
		id: 21,
		title: "Creative Story Generator",
		description:
			"Generate engaging short stories with complex characters and plot twists.",
		image: "/browse/creative-story.png",
		price: 0.1,
		category: "Creative Writing",
		rating: 4.8,
		seller: "Alice.sol",
	},
	{
		id: 22,
		title: "Poetry Composer",
		description: "Create beautiful poems with inspiring imagery and metaphors.",
		image: "/browse/poetry.png",
		price: 0.09,
		category: "Creative Writing",
		rating: 4.7,
		seller: "VerseMaster.sol",
	},
	{
		id: 23,
		title: "Screenplay Outline Generator",
		description:
			"Draft outlines for captivating screenplays with structured acts and scenes.",
		image: "/browse/screenplay.png",
		price: 0.12,
		category: "Creative Writing",
		rating: 4.6,
		seller: "ScriptWizard.sol",
	},
	{
		id: 24,
		title: "Character Development Assistant",
		description:
			"Develop deep and complex characters for your next masterpiece.",
		image: "/browse/character.png",
		price: 0.11,
		category: "Creative Writing",
		rating: 4.7,
		seller: "CharacterPro.sol",
	},
	{
		id: 25,
		title: "Dialogue Enhancer",
		description:
			"Improve dialogue tone and natural flow for your creative writing projects.",
		image: "/browse/dialogue.png",
		price: 0.1,
		category: "Creative Writing",
		rating: 4.5,
		seller: "Dialogue.sol",
	},
	{
		id: 26,
		title: "Plot Twist Generator",
		description: "Inject unexpected plot twists to keep your readers engaged.",
		image: "/browse/plot-twist.png",
		price: 0.13,
		category: "Creative Writing",
		rating: 4.8,
		seller: "TwistMaster.sol",
	},
	{
		id: 27,
		title: "Setting Creator",
		description:
			"Generate vivid settings and world-building details for your story.",
		image: "/browse/setting-creator.png",
		price: 0.09,
		category: "Creative Writing",
		rating: 4.6,
		seller: "WorldWeaver.sol",
	},
	{
		id: 28,
		title: "Narrative Voice Assistant",
		description:
			"Refine the narrative voice and tone in your creative writing piece.",
		image: "/browse/narrative.png",
		price: 0.1,
		category: "Creative Writing",
		rating: 4.7,
		seller: "Narrate.sol",
	},
	{
		id: 29,
		title: "Short Story Prompt",
		description: "Kickstart your writing with a unique short story prompt.",
		image: "/browse/short-story.png",
		price: 0.08,
		category: "Creative Writing",
		rating: 4.5,
		seller: "StorySpark.sol",
	},
	{
		id: 30,
		title: "Visual Writing Prompt",
		description:
			"Generate creative visual cues to inspire your next writing project.",
		image: "/browse/visual-writing.png",
		price: 0.1,
		category: "Creative Writing",
		rating: 4.7,
		seller: "VisioWord.sol",
	},
];

export const businessPrompts = [
	{
		id: 31,
		title: "Business Strategy Advisor",
		description:
			"Receive strategic insights and recommendations to optimize your business operations.",
		image: "/browse/business.png",
		price: 0.2,
		category: "Business",
		rating: 4.9,
		seller: "BizIntel.sol",
	},
	{
		id: 32,
		title: "Market Analysis Generator",
		description:
			"Generate comprehensive market analysis reports based on current trends and data.",
		image: "/browse/market-analysis.png",
		price: 0.15,
		category: "Business",
		rating: 4.7,
		seller: "MarketGuru.sol",
	},
	{
		id: 33,
		title: "Financial Forecasting Tool",
		description:
			"Create detailed financial forecasts and budget recommendations for businesses.",
		image: "/browse/financial-forecasting.png",
		price: 0.25,
		category: "Business",
		rating: 4.8,
		seller: "FinancePro.sol",
	},
	{
		id: 34,
		title: "Operational Efficiency Analyzer",
		description:
			"Analyze your business operations to identify opportunities for efficiency improvements.",
		image: "/browse/operational.png",
		price: 0.18,
		category: "Business",
		rating: 4.6,
		seller: "OpsExpert.sol",
	},
	{
		id: 35,
		title: "Risk Management Advisor",
		description:
			"Receive expert advice on identifying and mitigating business risks.",
		image: "/browse/risk-management.png",
		price: 0.2,
		category: "Business",
		rating: 4.7,
		seller: "RiskMaster.sol",
	},
	{
		id: 36,
		title: "Supply Chain Optimizer",
		description:
			"Streamline your supply chain operations to reduce costs and increase reliability.",
		image: "/browse/supply-chain.png",
		price: 0.22,
		category: "Business",
		rating: 4.8,
		seller: "ChainPro.sol",
	},
	{
		id: 37,
		title: "Customer Insights Generator",
		description:
			"Generate actionable insights based on customer data and behavior.",
		image: "/browse/customer.png",
		price: 0.17,
		category: "Business",
		rating: 4.7,
		seller: "Insight.sol",
	},
	{
		id: 38,
		title: "Investor Pitch Deck Creator",
		description:
			"Develop compelling pitch decks to attract investors for your startup.",
		image: "/browse/investor.png",
		price: 0.23,
		category: "Business",
		rating: 4.8,
		seller: "PitchPro.sol",
	},
	{
		id: 39,
		title: "Business Plan Outliner",
		description:
			"Create comprehensive business plans with in-depth market and operational insights.",
		image: "/browse/business-plan.png",
		price: 0.19,
		category: "Business",
		rating: 4.6,
		seller: "PlanMaster.sol",
	},
	{
		id: 40,
		title: "Sales Forecasting Tool",
		description:
			"Predict sales trends and enhance performance using advanced analytics.",
		image: "/browse/sales.png",
		price: 0.2,
		category: "Business",
		rating: 4.7,
		seller: "SalesGuru.sol",
	},
];
